language : cpp
sudo: false

compiler:
  - gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"




script : 
- cd src
-  make all 
-  cd ../bin 
- ./Sin.x -i ../inp/input.dat
- cd result
- ls -al ./

